Python prints the stack trace when the code throws an exception.
Hold information about the source of the problem.
Contains the function calls made before the error occurs.
